version: '3.4'

x-app: &common
  privileged: true
  environment:
    PYTHONUNBUFFERED: 1
    QT_X11_NO_MITSHM: 1
    DISPLAY: $DISPLAY
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
  build:
    context: .
    args: &common-args
      ROS_DISTRO: "melodic"
      BASE_IMAGE: nvidia/opengl:1.1-glvnd-runtime-ubuntu18.04


services:
  # This configuration builds the project for computers with NVIDIA hardware
  nvidia-ros: 
    <<: *common
    runtime: nvidia
    tty: true
    stdin_open: true
    networks:
      pr2_ros_network:
        ipv4_address: 172.19.0.3

  # This is the default for computers that don't have nvidia hardware accelerators
  ros:
    <<: *common
    #command: ["/bin/bash"]
    tty: true
    stdin_open: true
    networks:
      pr2_ros_network:
        ipv4_address: 172.19.0.2
    build:
      context: .
      args:
        <<: *common-args
        BASE_IMAGE: osrf/ros:melodic-desktop-full

networks:
  pr2_ros_network:
    external: true